services:
  postbot:
    image: philippbtz/mattermost-postbot:latest
    volumes:
      - ./.env:/app/.env:ro,z
      - ./data/postbot:/app/data:z
    networks:
      - internal
    restart: unless-stopped

  webui:
    image: philippbtz/mattermost-webui:latest
    env_file: .env
    ports:
      - "8080:8080"
    networks:
      - internal
    depends_on:
      - postbot
    volumes:
      - ./data/webui:/app/data:z
      - ./data/certs:/app/certs:ro,z
    restart: unless-stopped

networks:
  internal:
    driver: bridge